# Generated by Django 6.1 on 2026-08-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="about",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="address",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="handle",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="picture",
        ),
    ]
